// biomes.js — cubiomes technical biome id -> localized display name.
// English falls back to prettified technical names (which match the official
// English names); FR/ES/DE carry explicit tables. Loaded after i18n.js;
// also required by the Node test suite.
'use strict';

const BIOME_NAMES = {
  fr: {
    badlands: 'Badlands',
    badlands_plateau: 'Plateau de badlands',
    bamboo_jungle: 'Jungle de bambous',
    bamboo_jungle_hills: 'Collines de jungle de bambous',
    basalt_deltas: 'Deltas de basalte',
    beach: 'Plage',
    birch_forest: 'Forêt de bouleaux',
    birch_forest_hills: 'Collines de forêt de bouleaux',
    cherry_grove: 'Bosquet de cerisiers',
    cold_ocean: 'Océan froid',
    crimson_forest: 'Forêt carmin',
    dark_forest: 'Forêt sombre',
    dark_forest_hills: 'Collines de forêt sombre',
    deep_cold_ocean: 'Océan froid profond',
    deep_dark: 'Profondeurs sombres',
    deep_frozen_ocean: 'Océan gelé profond',
    deep_lukewarm_ocean: 'Océan tiède profond',
    deep_ocean: 'Océan profond',
    deep_warm_ocean: 'Océan chaud profond',
    desert: 'Désert',
    desert_hills: 'Collines désertiques',
    desert_lakes: 'Lacs désertiques',
    dripstone_caves: 'Grottes de spéléothèmes',
    end_barrens: "Terres stériles de l'End",
    end_highlands: "Hautes terres de l'End",
    end_midlands: "Terres médianes de l'End",
    eroded_badlands: 'Badlands érodées',
    flower_forest: 'Forêt fleurie',
    forest: 'Forêt',
    frozen_ocean: 'Océan gelé',
    frozen_peaks: 'Pics gelés',
    frozen_river: 'Rivière gelée',
    giant_spruce_taiga_hills: 'Collines de taïga de sapins géants',
    giant_tree_taiga_hills: "Collines de taïga d'arbres géants",
    grove: 'Bosquet enneigé',
    ice_spikes: 'Pics de glace',
    jagged_peaks: 'Pics déchiquetés',
    jungle: 'Jungle',
    jungle_hills: 'Collines de jungle',
    lukewarm_ocean: 'Océan tiède',
    lush_caves: 'Grottes luxuriantes',
    mangrove_swamp: 'Marais de mangrove',
    meadow: 'Prairie alpine',
    modified_badlands_plateau: 'Plateau de badlands modifié',
    modified_gravelly_mountains: 'Montagnes gravillonneuses modifiées',
    modified_jungle: 'Jungle modifiée',
    modified_jungle_edge: 'Lisière de jungle modifiée',
    modified_wooded_badlands_plateau: 'Plateau de badlands boisé modifié',
    mountain_edge: 'Lisière de montagne',
    mushroom_field_shore: 'Rivage de champs de champignons',
    mushroom_fields: 'Champs de champignons',
    nether_wastes: 'Terres désolées du Nether',
    ocean: 'Océan',
    old_growth_birch_forest: 'Forêt ancienne de bouleaux',
    old_growth_pine_taiga: 'Taïga ancienne de pins',
    old_growth_spruce_taiga: 'Taïga ancienne de sapins',
    pale_garden: 'Jardin pâle',
    plains: 'Plaines',
    rainforest: 'Forêt tropicale',
    river: 'Rivière',
    savanna: 'Savane',
    savanna_plateau: 'Plateau de savane',
    seasonal_forest: 'Forêt saisonnière',
    shattered_savanna_plateau: 'Plateau de savane accidenté',
    shrubland: 'Lande arbustive',
    small_end_islands: "Petites îles de l'End",
    snowy_beach: 'Plage enneigée',
    snowy_mountains: 'Montagnes enneigées',
    snowy_plains: 'Plaines enneigées',
    snowy_slopes: 'Pentes enneigées',
    snowy_taiga: 'Taïga enneigée',
    snowy_taiga_hills: 'Collines de taïga enneigée',
    snowy_taiga_mountains: 'Montagnes de taïga enneigée',
    soul_sand_valley: 'Vallée de sable des âmes',
    sparse_jungle: 'Jungle clairsemée',
    stony_peaks: 'Pics rocheux',
    stony_shore: 'Rivage rocheux',
    sunflower_plains: 'Plaines de tournesols',
    swamp: 'Marais',
    swamp_hills: 'Collines de marais',
    taiga: 'Taïga',
    taiga_hills: 'Collines de taïga',
    taiga_mountains: 'Montagnes de taïga',
    tall_birch_hills: 'Collines de grands bouleaux',
    the_end: "L'End",
    the_void: 'Le Vide',
    warm_ocean: 'Océan chaud',
    warped_forest: 'Forêt biscornue',
    windswept_forest: 'Forêt balayée par les vents',
    windswept_gravelly_hills: 'Collines gravillonneuses balayées par les vents',
    windswept_hills: 'Collines balayées par les vents',
    windswept_savanna: 'Savane balayée par les vents',
    wooded_badlands: 'Badlands boisées',
    wooded_hills: 'Collines boisées'
  },
  es: {
    badlands: 'Badlands',
    badlands_plateau: 'Meseta de badlands',
    bamboo_jungle: 'Jungla de bambú',
    bamboo_jungle_hills: 'Colinas de jungla de bambú',
    basalt_deltas: 'Deltas de basalto',
    beach: 'Playa',
    birch_forest: 'Bosque de abedules',
    birch_forest_hills: 'Colinas de bosque de abedules',
    cherry_grove: 'Arboleda de cerezos',
    cold_ocean: 'Océano frío',
    crimson_forest: 'Bosque carmesí',
    dark_forest: 'Bosque oscuro',
    dark_forest_hills: 'Colinas de bosque oscuro',
    deep_cold_ocean: 'Océano frío profundo',
    deep_dark: 'Oscuridad profunda',
    deep_frozen_ocean: 'Océano helado profundo',
    deep_lukewarm_ocean: 'Océano templado profundo',
    deep_ocean: 'Océano profundo',
    deep_warm_ocean: 'Océano cálido profundo',
    desert: 'Desierto',
    desert_hills: 'Colinas desérticas',
    desert_lakes: 'Lagos desérticos',
    dripstone_caves: 'Cuevas kársticas',
    end_barrens: 'Páramos del End',
    end_highlands: 'Tierras altas del End',
    end_midlands: 'Tierras medias del End',
    eroded_badlands: 'Badlands erosionados',
    flower_forest: 'Bosque floral',
    forest: 'Bosque',
    frozen_ocean: 'Océano helado',
    frozen_peaks: 'Picos helados',
    frozen_river: 'Río helado',
    giant_spruce_taiga_hills: 'Colinas de taiga de píceas gigantes',
    giant_tree_taiga_hills: 'Colinas de taiga de árboles gigantes',
    grove: 'Arboleda nevada',
    ice_spikes: 'Picos de hielo',
    jagged_peaks: 'Picos dentados',
    jungle: 'Jungla',
    jungle_hills: 'Colinas de jungla',
    lukewarm_ocean: 'Océano templado',
    lush_caves: 'Cuevas frondosas',
    mangrove_swamp: 'Pantano de manglar',
    meadow: 'Pradera alpina',
    modified_badlands_plateau: 'Meseta de badlands modificada',
    modified_gravelly_mountains: 'Montañas de grava modificadas',
    modified_jungle: 'Jungla modificada',
    modified_jungle_edge: 'Linde de jungla modificada',
    modified_wooded_badlands_plateau: 'Meseta de badlands arbolada modificada',
    mountain_edge: 'Borde de montaña',
    mushroom_field_shore: 'Costa de campo de champiñones',
    mushroom_fields: 'Campo de champiñones',
    nether_wastes: 'Páramos del Nether',
    ocean: 'Océano',
    old_growth_birch_forest: 'Bosque viejo de abedules',
    old_growth_pine_taiga: 'Taiga vieja de pinos',
    old_growth_spruce_taiga: 'Taiga vieja de píceas',
    pale_garden: 'Jardín pálido',
    plains: 'Llanura',
    rainforest: 'Selva tropical',
    river: 'Río',
    savanna: 'Sabana',
    savanna_plateau: 'Meseta de sabana',
    seasonal_forest: 'Bosque estacional',
    shattered_savanna_plateau: 'Meseta de sabana fragmentada',
    shrubland: 'Matorral',
    small_end_islands: 'Islas pequeñas del End',
    snowy_beach: 'Playa nevada',
    snowy_mountains: 'Montañas nevadas',
    snowy_plains: 'Llanura nevada',
    snowy_slopes: 'Laderas nevadas',
    snowy_taiga: 'Taiga nevada',
    snowy_taiga_hills: 'Colinas de taiga nevada',
    snowy_taiga_mountains: 'Montañas de taiga nevada',
    soul_sand_valley: 'Valle de arena de almas',
    sparse_jungle: 'Jungla dispersa',
    stony_peaks: 'Picos pedregosos',
    stony_shore: 'Costa pedregosa',
    sunflower_plains: 'Llanura de girasoles',
    swamp: 'Pantano',
    swamp_hills: 'Colinas de pantano',
    taiga: 'Taiga',
    taiga_hills: 'Colinas de taiga',
    taiga_mountains: 'Montañas de taiga',
    tall_birch_hills: 'Colinas de abedules altos',
    the_end: 'El End',
    the_void: 'El Vacío',
    warm_ocean: 'Océano cálido',
    warped_forest: 'Bosque distorsionado',
    windswept_forest: 'Bosque azotado por el viento',
    windswept_gravelly_hills: 'Colinas de grava azotadas por el viento',
    windswept_hills: 'Colinas azotadas por el viento',
    windswept_savanna: 'Sabana azotada por el viento',
    wooded_badlands: 'Badlands arbolados',
    wooded_hills: 'Colinas arboladas'
  },
  de: {
    badlands: 'Tafelberge',
    badlands_plateau: 'Tafelberghochebene',
    bamboo_jungle: 'Bambusdschungel',
    bamboo_jungle_hills: 'Bambusdschungelhügel',
    basalt_deltas: 'Basaltdeltas',
    beach: 'Strand',
    birch_forest: 'Birkenwald',
    birch_forest_hills: 'Birkenwaldhügel',
    cherry_grove: 'Kirschhain',
    cold_ocean: 'Kalter Ozean',
    crimson_forest: 'Karmesinwald',
    dark_forest: 'Finsterwald',
    dark_forest_hills: 'Finsterwaldhügel',
    deep_cold_ocean: 'Tiefer kalter Ozean',
    deep_dark: 'Tiefes Dunkel',
    deep_frozen_ocean: 'Tiefer vereister Ozean',
    deep_lukewarm_ocean: 'Tiefer lauwarmer Ozean',
    deep_ocean: 'Tiefer Ozean',
    deep_warm_ocean: 'Tiefer warmer Ozean',
    desert: 'Wüste',
    desert_hills: 'Wüstenhügel',
    desert_lakes: 'Wüstenseen',
    dripstone_caves: 'Tropfsteinhöhlen',
    end_barrens: 'Endödland',
    end_highlands: 'Endhochland',
    end_midlands: 'Endmittelland',
    eroded_badlands: 'Erodierte Tafelberge',
    flower_forest: 'Blumenwald',
    forest: 'Wald',
    frozen_ocean: 'Vereister Ozean',
    frozen_peaks: 'Vereiste Gipfel',
    frozen_river: 'Vereister Fluss',
    giant_spruce_taiga_hills: 'Hügel der Riesenfichtentaiga',
    giant_tree_taiga_hills: 'Hügel der Riesenbaumtaiga',
    grove: 'Verschneiter Hain',
    ice_spikes: 'Eiszapfen',
    jagged_peaks: 'Zerklüftete Gipfel',
    jungle: 'Dschungel',
    jungle_hills: 'Dschungelhügel',
    lukewarm_ocean: 'Lauwarmer Ozean',
    lush_caves: 'Üppige Höhlen',
    mangrove_swamp: 'Mangrovensumpf',
    meadow: 'Almwiese',
    modified_badlands_plateau: 'Abgewandelte Tafelberghochebene',
    modified_gravelly_mountains: 'Abgewandelte Geröllberge',
    modified_jungle: 'Abgewandelter Dschungel',
    modified_jungle_edge: 'Abgewandelter Dschungelrand',
    modified_wooded_badlands_plateau: 'Abgewandelte bewaldete Tafelberghochebene',
    mountain_edge: 'Bergrand',
    mushroom_field_shore: 'Pilzlandküste',
    mushroom_fields: 'Pilzland',
    nether_wastes: 'Netherödland',
    ocean: 'Ozean',
    old_growth_birch_forest: 'Birkenurwald',
    old_growth_pine_taiga: 'Kiefernurtaiga',
    old_growth_spruce_taiga: 'Fichtenurtaiga',
    pale_garden: 'Fahler Garten',
    plains: 'Ebene',
    rainforest: 'Regenwald',
    river: 'Fluss',
    savanna: 'Savanne',
    savanna_plateau: 'Savannenhochebene',
    seasonal_forest: 'Jahreszeitenwald',
    shattered_savanna_plateau: 'Zerrüttete Savannenhochebene',
    shrubland: 'Buschland',
    small_end_islands: 'Kleine Endinseln',
    snowy_beach: 'Verschneiter Strand',
    snowy_mountains: 'Verschneite Berge',
    snowy_plains: 'Verschneite Ebene',
    snowy_slopes: 'Verschneite Hänge',
    snowy_taiga: 'Verschneite Taiga',
    snowy_taiga_hills: 'Verschneite Taigahügel',
    snowy_taiga_mountains: 'Verschneite Taigaberge',
    soul_sand_valley: 'Seelensandtal',
    sparse_jungle: 'Lichter Dschungel',
    stony_peaks: 'Steinige Gipfel',
    stony_shore: 'Steinige Küste',
    sunflower_plains: 'Sonnenblumenebene',
    swamp: 'Sumpf',
    swamp_hills: 'Sumpfhügel',
    taiga: 'Taiga',
    taiga_hills: 'Taigahügel',
    taiga_mountains: 'Taigaberge',
    tall_birch_hills: 'Hohe Birkenhügel',
    the_end: 'Das Ende',
    the_void: 'Die Leere',
    warm_ocean: 'Warmer Ozean',
    warped_forest: 'Wirrwald',
    windswept_forest: 'Windgepeitschter Wald',
    windswept_gravelly_hills: 'Windgepeitschte Geröllhügel',
    windswept_hills: 'Windgepeitschte Hügel',
    windswept_savanna: 'Windgepeitschte Savanne',
    wooded_badlands: 'Bewaldete Tafelberge',
    wooded_hills: 'Bewaldete Hügel'
  }
};

// "cherry_grove" -> "Cherry Grove"; matches the official English biome names.
function prettifyBiome(name) {
  return String(name).split('_').map((w) => (w ? w[0].toUpperCase() + w.slice(1) : w)).join(' ');
}

// Localized label for a technical biome name; lang defaults to the UI
// language (currentLang from i18n.js), unknown entries fall back to English.
function biomeLabel(name, lang) {
  const l = lang || (typeof currentLang !== 'undefined' ? currentLang : 'en');
  return (BIOME_NAMES[l] && BIOME_NAMES[l][name]) || prettifyBiome(name);
}

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { BIOME_NAMES, biomeLabel, prettifyBiome };
}
