// biomes.js — cubiomes technical biome id -> localized display name.
// English falls back to prettified technical names (which match the official
// English names); the other languages carry explicit tables. ES module, circular with
// i18n.js (each only calls the other's bindings at call time); also imported
// by the Node test suite.
import { currentLang } from './i18n.js';

export const BIOME_NAMES = {
  fr: {
    badlands: 'Badlands',
    badlands_plateau: 'Plateau de badlands',
    bamboo_jungle: 'Jungle de bambous',
    bamboo_jungle_hills: 'Collines de jungle de bambous',
    basalt_deltas: 'Deltas de basalte',
    beach: 'Plage',
    birch_forest: 'Forêt de bouleaux',
    birch_forest_hills: 'Collines de forêt de bouleaux',
    cherry_grove: 'Bosquet de cerisiers',
    cold_ocean: 'Océan froid',
    crimson_forest: 'Forêt carmin',
    dark_forest: 'Forêt sombre',
    dark_forest_hills: 'Collines de forêt sombre',
    deep_cold_ocean: 'Océan froid profond',
    deep_dark: 'Profondeurs sombres',
    deep_frozen_ocean: 'Océan gelé profond',
    deep_lukewarm_ocean: 'Océan tiède profond',
    deep_ocean: 'Océan profond',
    deep_warm_ocean: 'Océan chaud profond',
    desert: 'Désert',
    desert_hills: 'Collines désertiques',
    desert_lakes: 'Lacs désertiques',
    dripstone_caves: 'Grottes de spéléothèmes',
    end_barrens: "Terres stériles de l'End",
    end_highlands: "Hautes terres de l'End",
    end_midlands: "Terres médianes de l'End",
    eroded_badlands: 'Badlands érodées',
    flower_forest: 'Forêt fleurie',
    forest: 'Forêt',
    frozen_ocean: 'Océan gelé',
    frozen_peaks: 'Pics gelés',
    frozen_river: 'Rivière gelée',
    giant_spruce_taiga_hills: 'Collines de taïga de sapins géants',
    giant_tree_taiga_hills: "Collines de taïga d'arbres géants",
    grove: 'Bosquet enneigé',
    ice_spikes: 'Pics de glace',
    jagged_peaks: 'Pics déchiquetés',
    jungle: 'Jungle',
    jungle_hills: 'Collines de jungle',
    lukewarm_ocean: 'Océan tiède',
    lush_caves: 'Grottes luxuriantes',
    mangrove_swamp: 'Marais de mangrove',
    meadow: 'Prairie alpine',
    modified_badlands_plateau: 'Plateau de badlands modifié',
    modified_gravelly_mountains: 'Montagnes gravillonneuses modifiées',
    modified_jungle: 'Jungle modifiée',
    modified_jungle_edge: 'Lisière de jungle modifiée',
    modified_wooded_badlands_plateau: 'Plateau de badlands boisé modifié',
    mountain_edge: 'Lisière de montagne',
    mushroom_field_shore: 'Rivage de champs de champignons',
    mushroom_fields: 'Champs de champignons',
    nether_wastes: 'Terres désolées du Nether',
    ocean: 'Océan',
    old_growth_birch_forest: 'Forêt ancienne de bouleaux',
    old_growth_pine_taiga: 'Taïga ancienne de pins',
    old_growth_spruce_taiga: 'Taïga ancienne de sapins',
    pale_garden: 'Jardin pâle',
    plains: 'Plaines',
    rainforest: 'Forêt tropicale',
    river: 'Rivière',
    savanna: 'Savane',
    savanna_plateau: 'Plateau de savane',
    seasonal_forest: 'Forêt saisonnière',
    shattered_savanna_plateau: 'Plateau de savane accidenté',
    shrubland: 'Lande arbustive',
    small_end_islands: "Petites îles de l'End",
    snowy_beach: 'Plage enneigée',
    snowy_mountains: 'Montagnes enneigées',
    snowy_plains: 'Plaines enneigées',
    snowy_slopes: 'Pentes enneigées',
    snowy_taiga: 'Taïga enneigée',
    snowy_taiga_hills: 'Collines de taïga enneigée',
    snowy_taiga_mountains: 'Montagnes de taïga enneigée',
    soul_sand_valley: 'Vallée de sable des âmes',
    sparse_jungle: 'Jungle clairsemée',
    stony_peaks: 'Pics rocheux',
    stony_shore: 'Rivage rocheux',
    sunflower_plains: 'Plaines de tournesols',
    swamp: 'Marais',
    swamp_hills: 'Collines de marais',
    taiga: 'Taïga',
    taiga_hills: 'Collines de taïga',
    taiga_mountains: 'Montagnes de taïga',
    tall_birch_hills: 'Collines de grands bouleaux',
    the_end: "L'End",
    the_void: 'Le Vide',
    warm_ocean: 'Océan chaud',
    warped_forest: 'Forêt biscornue',
    windswept_forest: 'Forêt balayée par les vents',
    windswept_gravelly_hills: 'Collines gravillonneuses balayées par les vents',
    windswept_hills: 'Collines balayées par les vents',
    windswept_savanna: 'Savane balayée par les vents',
    wooded_badlands: 'Badlands boisées',
    wooded_hills: 'Collines boisées',
    // legacy pre-1.18 biome names
    giant_spruce_taiga: "Taïga aux sapins géants",
    giant_tree_taiga: "Taïga aux arbres géants",
    gravelly_mountains: "Montagnes graveleuses",
    jungle_edge: "Lisière de jungle",
    mountains: "Montagnes",
    shattered_savanna: "Savane délabrée",
    snowy_tundra: "Toundra enneigée",
    stone_shore: "Rivage rocheux",
    tall_birch_forest: "Forêt de grands bouleaux",
    wooded_badlands_plateau: "Plateau de badlands boisé",
    wooded_mountains: "Montagnes boisées",
  },
  es: {
    badlands: 'Badlands',
    badlands_plateau: 'Meseta de badlands',
    bamboo_jungle: 'Jungla de bambú',
    bamboo_jungle_hills: 'Colinas de jungla de bambú',
    basalt_deltas: 'Deltas de basalto',
    beach: 'Playa',
    birch_forest: 'Bosque de abedules',
    birch_forest_hills: 'Colinas de bosque de abedules',
    cherry_grove: 'Arboleda de cerezos',
    cold_ocean: 'Océano frío',
    crimson_forest: 'Bosque carmesí',
    dark_forest: 'Bosque oscuro',
    dark_forest_hills: 'Colinas de bosque oscuro',
    deep_cold_ocean: 'Océano frío profundo',
    deep_dark: 'Oscuridad profunda',
    deep_frozen_ocean: 'Océano helado profundo',
    deep_lukewarm_ocean: 'Océano templado profundo',
    deep_ocean: 'Océano profundo',
    deep_warm_ocean: 'Océano cálido profundo',
    desert: 'Desierto',
    desert_hills: 'Colinas desérticas',
    desert_lakes: 'Lagos desérticos',
    dripstone_caves: 'Cuevas kársticas',
    end_barrens: 'Páramos del End',
    end_highlands: 'Tierras altas del End',
    end_midlands: 'Tierras medias del End',
    eroded_badlands: 'Badlands erosionados',
    flower_forest: 'Bosque floral',
    forest: 'Bosque',
    frozen_ocean: 'Océano helado',
    frozen_peaks: 'Picos helados',
    frozen_river: 'Río helado',
    giant_spruce_taiga_hills: 'Colinas de taiga de píceas gigantes',
    giant_tree_taiga_hills: 'Colinas de taiga de árboles gigantes',
    grove: 'Arboleda nevada',
    ice_spikes: 'Picos de hielo',
    jagged_peaks: 'Picos dentados',
    jungle: 'Jungla',
    jungle_hills: 'Colinas de jungla',
    lukewarm_ocean: 'Océano templado',
    lush_caves: 'Cuevas frondosas',
    mangrove_swamp: 'Pantano de manglar',
    meadow: 'Pradera alpina',
    modified_badlands_plateau: 'Meseta de badlands modificada',
    modified_gravelly_mountains: 'Montañas de grava modificadas',
    modified_jungle: 'Jungla modificada',
    modified_jungle_edge: 'Linde de jungla modificada',
    modified_wooded_badlands_plateau: 'Meseta de badlands arbolada modificada',
    mountain_edge: 'Borde de montaña',
    mushroom_field_shore: 'Costa de campo de champiñones',
    mushroom_fields: 'Campo de champiñones',
    nether_wastes: 'Páramos del Nether',
    ocean: 'Océano',
    old_growth_birch_forest: 'Bosque viejo de abedules',
    old_growth_pine_taiga: 'Taiga vieja de pinos',
    old_growth_spruce_taiga: 'Taiga vieja de píceas',
    pale_garden: 'Jardín pálido',
    plains: 'Llanura',
    rainforest: 'Selva tropical',
    river: 'Río',
    savanna: 'Sabana',
    savanna_plateau: 'Meseta de sabana',
    seasonal_forest: 'Bosque estacional',
    shattered_savanna_plateau: 'Meseta de sabana fragmentada',
    shrubland: 'Matorral',
    small_end_islands: 'Islas pequeñas del End',
    snowy_beach: 'Playa nevada',
    snowy_mountains: 'Montañas nevadas',
    snowy_plains: 'Llanura nevada',
    snowy_slopes: 'Laderas nevadas',
    snowy_taiga: 'Taiga nevada',
    snowy_taiga_hills: 'Colinas de taiga nevada',
    snowy_taiga_mountains: 'Montañas de taiga nevada',
    soul_sand_valley: 'Valle de arena de almas',
    sparse_jungle: 'Jungla dispersa',
    stony_peaks: 'Picos pedregosos',
    stony_shore: 'Costa pedregosa',
    sunflower_plains: 'Llanura de girasoles',
    swamp: 'Pantano',
    swamp_hills: 'Colinas de pantano',
    taiga: 'Taiga',
    taiga_hills: 'Colinas de taiga',
    taiga_mountains: 'Montañas de taiga',
    tall_birch_hills: 'Colinas de abedules altos',
    the_end: 'El End',
    the_void: 'El Vacío',
    warm_ocean: 'Océano cálido',
    warped_forest: 'Bosque distorsionado',
    windswept_forest: 'Bosque azotado por el viento',
    windswept_gravelly_hills: 'Colinas de grava azotadas por el viento',
    windswept_hills: 'Colinas azotadas por el viento',
    windswept_savanna: 'Sabana azotada por el viento',
    wooded_badlands: 'Badlands arbolados',
    wooded_hills: 'Colinas arboladas',
    // legacy pre-1.18 biome names
    giant_spruce_taiga: "Taiga de píceas gigantes",
    giant_tree_taiga: "Taiga de árboles gigantes",
    gravelly_mountains: "Montañas de grava",
    jungle_edge: "Linde de jungla",
    mountains: "Montañas",
    shattered_savanna: "Sabana destrozada",
    snowy_tundra: "Tundra nevada",
    stone_shore: "Orilla de piedra",
    tall_birch_forest: "Bosque de abedules altos",
    wooded_badlands_plateau: "Meseta de badlands arbolada",
    wooded_mountains: "Montañas arboladas",
  },
  de: {
    badlands: 'Tafelberge',
    badlands_plateau: 'Tafelberghochebene',
    bamboo_jungle: 'Bambusdschungel',
    bamboo_jungle_hills: 'Bambusdschungelhügel',
    basalt_deltas: 'Basaltdeltas',
    beach: 'Strand',
    birch_forest: 'Birkenwald',
    birch_forest_hills: 'Birkenwaldhügel',
    cherry_grove: 'Kirschhain',
    cold_ocean: 'Kalter Ozean',
    crimson_forest: 'Karmesinwald',
    dark_forest: 'Finsterwald',
    dark_forest_hills: 'Finsterwaldhügel',
    deep_cold_ocean: 'Tiefer kalter Ozean',
    deep_dark: 'Tiefes Dunkel',
    deep_frozen_ocean: 'Tiefer vereister Ozean',
    deep_lukewarm_ocean: 'Tiefer lauwarmer Ozean',
    deep_ocean: 'Tiefer Ozean',
    deep_warm_ocean: 'Tiefer warmer Ozean',
    desert: 'Wüste',
    desert_hills: 'Wüstenhügel',
    desert_lakes: 'Wüstenseen',
    dripstone_caves: 'Tropfsteinhöhlen',
    end_barrens: 'Endödland',
    end_highlands: 'Endhochland',
    end_midlands: 'Endmittelland',
    eroded_badlands: 'Erodierte Tafelberge',
    flower_forest: 'Blumenwald',
    forest: 'Wald',
    frozen_ocean: 'Vereister Ozean',
    frozen_peaks: 'Vereiste Gipfel',
    frozen_river: 'Vereister Fluss',
    giant_spruce_taiga_hills: 'Hügel der Riesenfichtentaiga',
    giant_tree_taiga_hills: 'Hügel der Riesenbaumtaiga',
    grove: 'Verschneiter Hain',
    ice_spikes: 'Eiszapfen',
    jagged_peaks: 'Zerklüftete Gipfel',
    jungle: 'Dschungel',
    jungle_hills: 'Dschungelhügel',
    lukewarm_ocean: 'Lauwarmer Ozean',
    lush_caves: 'Üppige Höhlen',
    mangrove_swamp: 'Mangrovensumpf',
    meadow: 'Almwiese',
    modified_badlands_plateau: 'Abgewandelte Tafelberghochebene',
    modified_gravelly_mountains: 'Abgewandelte Geröllberge',
    modified_jungle: 'Abgewandelter Dschungel',
    modified_jungle_edge: 'Abgewandelter Dschungelrand',
    modified_wooded_badlands_plateau: 'Abgewandelte bewaldete Tafelberghochebene',
    mountain_edge: 'Bergrand',
    mushroom_field_shore: 'Pilzlandküste',
    mushroom_fields: 'Pilzland',
    nether_wastes: 'Netherödland',
    ocean: 'Ozean',
    old_growth_birch_forest: 'Birkenurwald',
    old_growth_pine_taiga: 'Kiefernurtaiga',
    old_growth_spruce_taiga: 'Fichtenurtaiga',
    pale_garden: 'Fahler Garten',
    plains: 'Ebene',
    rainforest: 'Regenwald',
    river: 'Fluss',
    savanna: 'Savanne',
    savanna_plateau: 'Savannenhochebene',
    seasonal_forest: 'Jahreszeitenwald',
    shattered_savanna_plateau: 'Zerrüttete Savannenhochebene',
    shrubland: 'Buschland',
    small_end_islands: 'Kleine Endinseln',
    snowy_beach: 'Verschneiter Strand',
    snowy_mountains: 'Verschneite Berge',
    snowy_plains: 'Verschneite Ebene',
    snowy_slopes: 'Verschneite Hänge',
    snowy_taiga: 'Verschneite Taiga',
    snowy_taiga_hills: 'Verschneite Taigahügel',
    snowy_taiga_mountains: 'Verschneite Taigaberge',
    soul_sand_valley: 'Seelensandtal',
    sparse_jungle: 'Lichter Dschungel',
    stony_peaks: 'Steinige Gipfel',
    stony_shore: 'Steinige Küste',
    sunflower_plains: 'Sonnenblumenebene',
    swamp: 'Sumpf',
    swamp_hills: 'Sumpfhügel',
    taiga: 'Taiga',
    taiga_hills: 'Taigahügel',
    taiga_mountains: 'Taigaberge',
    tall_birch_hills: 'Hohe Birkenhügel',
    the_end: 'Das Ende',
    the_void: 'Die Leere',
    warm_ocean: 'Warmer Ozean',
    warped_forest: 'Wirrwald',
    windswept_forest: 'Windgepeitschter Wald',
    windswept_gravelly_hills: 'Windgepeitschte Geröllhügel',
    windswept_hills: 'Windgepeitschte Hügel',
    windswept_savanna: 'Windgepeitschte Savanne',
    wooded_badlands: 'Bewaldete Tafelberge',
    wooded_hills: 'Bewaldete Hügel',
    // legacy pre-1.18 biome names
    giant_spruce_taiga: "Riesenfichtentaiga",
    giant_tree_taiga: "Riesenbaumtaiga",
    gravelly_mountains: "Geröllberge",
    jungle_edge: "Dschungelrand",
    mountains: "Berge",
    shattered_savanna: "Zerklüftete Savanne",
    snowy_tundra: "Verschneite Tundra",
    stone_shore: "Steinufer",
    tall_birch_forest: "Hoher Birkenwald",
    wooded_badlands_plateau: "Bewaldetes Tafelberg-Plateau",
    wooded_mountains: "Bewaldete Berge",
  },
  it: {
    badlands: "Calanchi",
    badlands_plateau: "Altopiano dei calanchi",
    bamboo_jungle: "Giungla di bambù",
    bamboo_jungle_hills: "Colline di giungla di bambù",
    basalt_deltas: "Delta di basalto",
    beach: "Spiaggia",
    birch_forest: "Foresta di betulle",
    birch_forest_hills: "Colline di foresta di betulle",
    cherry_grove: "Bosco di ciliegi",
    cold_ocean: "Oceano freddo",
    crimson_forest: "Foresta cremisi",
    dark_forest: "Foresta oscura",
    dark_forest_hills: "Colline di foresta oscura",
    deep_cold_ocean: "Oceano freddo profondo",
    deep_dark: "Oscurità profonda",
    deep_frozen_ocean: "Oceano ghiacciato profondo",
    deep_lukewarm_ocean: "Oceano tiepido profondo",
    deep_ocean: "Oceano profondo",
    deep_warm_ocean: "Oceano caldo profondo",
    desert: "Deserto",
    desert_hills: "Colline desertiche",
    desert_lakes: "Laghi desertici",
    dripstone_caves: "Grotte di speleotemi",
    end_barrens: "Lande dell'End",
    end_highlands: "Altopiani dell'End",
    end_midlands: "Terre mediane dell'End",
    eroded_badlands: "Calanchi erosi",
    flower_forest: "Foresta fiorita",
    forest: "Foresta",
    frozen_ocean: "Oceano ghiacciato",
    frozen_peaks: "Picchi ghiacciati",
    frozen_river: "Fiume ghiacciato",
    giant_spruce_taiga_hills: "Colline di taiga di abeti giganti",
    giant_tree_taiga_hills: "Colline di taiga di alberi giganti",
    grove: "Bosco innevato",
    ice_spikes: "Guglie di ghiaccio",
    jagged_peaks: "Picchi frastagliati",
    jungle: "Giungla",
    jungle_hills: "Colline di giungla",
    lukewarm_ocean: "Oceano tiepido",
    lush_caves: "Grotte lussureggianti",
    mangrove_swamp: "Palude di mangrovie",
    meadow: "Prateria alpina",
    modified_badlands_plateau: "Altopiano dei calanchi modificato",
    modified_gravelly_mountains: "Montagne ghiaiose modificate",
    modified_jungle: "Giungla modificata",
    modified_jungle_edge: "Margine di giungla modificato",
    modified_wooded_badlands_plateau: "Altopiano dei calanchi boscoso modificato",
    mountain_edge: "Margine di montagna",
    mushroom_field_shore: "Riva dei campi di funghi",
    mushroom_fields: "Campi di funghi",
    nether_wastes: "Lande del Nether",
    ocean: "Oceano",
    old_growth_birch_forest: "Foresta secolare di betulle",
    old_growth_pine_taiga: "Taiga secolare di pini",
    old_growth_spruce_taiga: "Taiga secolare di abeti",
    pale_garden: "Giardino pallido",
    plains: "Pianure",
    rainforest: "Foresta pluviale",
    river: "Fiume",
    savanna: "Savana",
    savanna_plateau: "Altopiano di savana",
    seasonal_forest: "Foresta stagionale",
    shattered_savanna_plateau: "Altopiano di savana frantumato",
    shrubland: "Arbusteto",
    small_end_islands: "Piccole isole dell'End",
    snowy_beach: "Spiaggia innevata",
    snowy_mountains: "Montagne innevate",
    snowy_plains: "Pianure innevate",
    snowy_slopes: "Pendii innevati",
    snowy_taiga: "Taiga innevata",
    snowy_taiga_hills: "Colline di taiga innevata",
    snowy_taiga_mountains: "Montagne di taiga innevata",
    soul_sand_valley: "Valle di sabbia delle anime",
    sparse_jungle: "Giungla rada",
    stony_peaks: "Picchi rocciosi",
    stony_shore: "Riva rocciosa",
    sunflower_plains: "Pianure di girasoli",
    swamp: "Palude",
    swamp_hills: "Colline di palude",
    taiga: "Taiga",
    taiga_hills: "Colline di taiga",
    taiga_mountains: "Montagne di taiga",
    tall_birch_hills: "Colline di betulle alte",
    the_end: "L'End",
    the_void: "Il Vuoto",
    warm_ocean: "Oceano caldo",
    warped_forest: "Foresta distorta",
    windswept_forest: "Foresta battuta dai venti",
    windswept_gravelly_hills: "Colline ghiaiose battute dai venti",
    windswept_hills: "Colline battute dai venti",
    windswept_savanna: "Savana battuta dai venti",
    wooded_badlands: "Calanchi boscosi",
    wooded_hills: "Colline boscose",
    // legacy pre-1.18 biome names
    giant_spruce_taiga: "Taiga degli abeti giganti",
    giant_tree_taiga: "Taiga degli alberi giganti",
    gravelly_mountains: "Montagne ghiaiose",
    jungle_edge: "Margine della giungla",
    mountains: "Montagne",
    shattered_savanna: "Savana frantumata",
    snowy_tundra: "Tundra innevata",
    stone_shore: "Riva rocciosa",
    tall_birch_forest: "Foresta di betulle alte",
    wooded_badlands_plateau: "Altopiano dei calanchi boscoso",
    wooded_mountains: "Montagne boscose",
  },
  pt: {
    badlands: "Ermo",
    badlands_plateau: "Platô do ermo",
    bamboo_jungle: "Selva de bambus",
    bamboo_jungle_hills: "Colinas de selva de bambus",
    basalt_deltas: "Deltas de basalto",
    beach: "Praia",
    birch_forest: "Floresta de bétulas",
    birch_forest_hills: "Colinas de floresta de bétulas",
    cherry_grove: "Bosque de cerejeiras",
    cold_ocean: "Oceano frio",
    crimson_forest: "Floresta carmesim",
    dark_forest: "Floresta sombria",
    dark_forest_hills: "Colinas de floresta sombria",
    deep_cold_ocean: "Oceano frio profundo",
    deep_dark: "Escuridão profunda",
    deep_frozen_ocean: "Oceano congelado profundo",
    deep_lukewarm_ocean: "Oceano morno profundo",
    deep_ocean: "Oceano profundo",
    deep_warm_ocean: "Oceano quente profundo",
    desert: "Deserto",
    desert_hills: "Colinas desérticas",
    desert_lakes: "Lagos desérticos",
    dripstone_caves: "Cavernas de espeleotemas",
    end_barrens: "Terras áridas do End",
    end_highlands: "Terras altas do End",
    end_midlands: "Terras médias do End",
    eroded_badlands: "Ermo erodido",
    flower_forest: "Floresta das flores",
    forest: "Floresta",
    frozen_ocean: "Oceano congelado",
    frozen_peaks: "Picos congelados",
    frozen_river: "Rio congelado",
    giant_spruce_taiga_hills: "Colinas de taiga de abetos gigantes",
    giant_tree_taiga_hills: "Colinas de taiga de árvores gigantes",
    grove: "Bosque nevado",
    ice_spikes: "Picos de gelo",
    jagged_peaks: "Picos irregulares",
    jungle: "Selva",
    jungle_hills: "Colinas de selva",
    lukewarm_ocean: "Oceano morno",
    lush_caves: "Cavernas exuberantes",
    mangrove_swamp: "Pântano de mangue",
    meadow: "Campina",
    modified_badlands_plateau: "Platô do ermo modificado",
    modified_gravelly_mountains: "Montanhas de cascalho modificadas",
    modified_jungle: "Selva modificada",
    modified_jungle_edge: "Borda de selva modificada",
    modified_wooded_badlands_plateau: "Platô do ermo arborizado modificado",
    mountain_edge: "Borda de montanha",
    mushroom_field_shore: "Litoral de campos de cogumelos",
    mushroom_fields: "Campos de cogumelos",
    nether_wastes: "Terras devastadas do Nether",
    ocean: "Oceano",
    old_growth_birch_forest: "Floresta antiga de bétulas",
    old_growth_pine_taiga: "Taiga antiga de pinheiros",
    old_growth_spruce_taiga: "Taiga antiga de abetos",
    pale_garden: "Jardim pálido",
    plains: "Planícies",
    rainforest: "Floresta tropical",
    river: "Rio",
    savanna: "Savana",
    savanna_plateau: "Platô de savana",
    seasonal_forest: "Floresta sazonal",
    shattered_savanna_plateau: "Platô de savana despedaçado",
    shrubland: "Matagal",
    small_end_islands: "Pequenas ilhas do End",
    snowy_beach: "Praia nevada",
    snowy_mountains: "Montanhas nevadas",
    snowy_plains: "Planícies nevadas",
    snowy_slopes: "Encostas nevadas",
    snowy_taiga: "Taiga nevada",
    snowy_taiga_hills: "Colinas de taiga nevada",
    snowy_taiga_mountains: "Montanhas de taiga nevada",
    soul_sand_valley: "Vale de areia das almas",
    sparse_jungle: "Selva esparsa",
    stony_peaks: "Picos rochosos",
    stony_shore: "Litoral rochoso",
    sunflower_plains: "Planícies de girassóis",
    swamp: "Pântano",
    swamp_hills: "Colinas de pântano",
    taiga: "Taiga",
    taiga_hills: "Colinas de taiga",
    taiga_mountains: "Montanhas de taiga",
    tall_birch_hills: "Colinas de bétulas altas",
    the_end: "O End",
    the_void: "O Vazio",
    warm_ocean: "Oceano quente",
    warped_forest: "Floresta deformada",
    windswept_forest: "Floresta varrida pelo vento",
    windswept_gravelly_hills: "Colinas de cascalho varridas pelo vento",
    windswept_hills: "Colinas varridas pelo vento",
    windswept_savanna: "Savana varrida pelo vento",
    wooded_badlands: "Ermo arborizado",
    wooded_hills: "Colinas arborizadas",
    // legacy pre-1.18 biome names
    giant_spruce_taiga: "Taiga de pinheiros gigantes",
    giant_tree_taiga: "Taiga de árvores gigantes",
    gravelly_mountains: "Montanhas cascalhentas",
    jungle_edge: "Borda de selva",
    mountains: "Montanhas",
    shattered_savanna: "Savana despedaçada",
    snowy_tundra: "Tundra nevada",
    stone_shore: "Costa de pedra",
    tall_birch_forest: "Floresta de bétulas altas",
    wooded_badlands_plateau: "Platô do ermo arborizado",
    wooded_mountains: "Montanhas arborizadas",
  },
  ja: {
    badlands: '荒野',
    badlands_plateau: '荒野の台地',
    bamboo_jungle: '竹林',
    bamboo_jungle_hills: '竹林の丘',
    basalt_deltas: '玄武岩の三角州',
    beach: '砂浜',
    birch_forest: 'シラカバの森',
    birch_forest_hills: 'シラカバの森の丘',
    cherry_grove: '桜の森',
    cold_ocean: '冷たい海',
    crimson_forest: '真紅の森',
    dark_forest: '暗い森',
    dark_forest_hills: '暗い森の丘',
    deep_cold_ocean: '冷たい深海',
    deep_dark: 'ディープダーク',
    deep_frozen_ocean: '凍った深海',
    deep_lukewarm_ocean: 'ぬるい深海',
    deep_ocean: '深海',
    deep_warm_ocean: '暖かい深海',
    desert: '砂漠',
    desert_hills: '砂漠の丘',
    desert_lakes: '砂漠の湖',
    dripstone_caves: '鍾乳洞',
    end_barrens: 'エンドの不毛地帯',
    end_highlands: 'エンドの高地',
    end_midlands: 'エンドの中央地帯',
    eroded_badlands: '浸食された荒野',
    flower_forest: '花の森',
    forest: '森林',
    frozen_ocean: '凍った海',
    frozen_peaks: '凍った山頂',
    frozen_river: '凍った川',
    giant_spruce_taiga_hills: '巨大トウヒタイガの丘',
    giant_tree_taiga_hills: '巨大樹タイガの丘',
    grove: '林',
    ice_spikes: '氷樹',
    jagged_peaks: '尖った山頂',
    jungle: 'ジャングル',
    jungle_hills: 'ジャングルの丘',
    lukewarm_ocean: 'ぬるい海',
    lush_caves: '繁茂した洞窟',
    mangrove_swamp: 'マングローブの沼地',
    meadow: '牧草地',
    modified_badlands_plateau: '変異した荒野の台地',
    modified_gravelly_mountains: '変異した砂利の山',
    modified_jungle: '変異したジャングル',
    modified_jungle_edge: '変異したジャングルの端',
    modified_wooded_badlands_plateau: '変異した森のある荒野の台地',
    mountain_edge: '山の端',
    mushroom_field_shore: 'キノコ島の海岸',
    mushroom_fields: 'キノコ島',
    nether_wastes: 'ネザーの荒地',
    ocean: '海洋',
    old_growth_birch_forest: '原生シラカバの森',
    old_growth_pine_taiga: '原生マツタイガ',
    old_growth_spruce_taiga: '原生トウヒタイガ',
    pale_garden: 'ペールガーデン',
    plains: '平原',
    rainforest: '熱帯雨林',
    river: '川',
    savanna: 'サバンナ',
    savanna_plateau: 'サバンナの台地',
    seasonal_forest: '季節の森',
    shattered_savanna_plateau: '荒廃したサバンナの台地',
    shrubland: '低木地',
    small_end_islands: 'エンドの小島',
    snowy_beach: '雪の砂浜',
    snowy_mountains: '雪山',
    snowy_plains: '雪原',
    snowy_slopes: '雪の斜面',
    snowy_taiga: '雪のタイガ',
    snowy_taiga_hills: '雪のタイガの丘',
    snowy_taiga_mountains: '雪のタイガの山',
    soul_sand_valley: 'ソウルサンドの谷',
    sparse_jungle: 'まばらなジャングル',
    stony_peaks: '石だらけの山頂',
    stony_shore: '石だらけの海岸',
    sunflower_plains: 'ヒマワリ平原',
    swamp: '沼地',
    swamp_hills: '沼地の丘',
    taiga: 'タイガ',
    taiga_hills: 'タイガの丘',
    taiga_mountains: 'タイガの山',
    tall_birch_hills: 'シラカバ原生林の丘',
    the_end: 'ジ・エンド',
    the_void: '奈落',
    warm_ocean: '暖かい海',
    warped_forest: '歪んだ森',
    windswept_forest: '吹きさらしの森',
    windswept_gravelly_hills: '吹きさらしの砂利の丘',
    windswept_hills: '吹きさらしの丘',
    windswept_savanna: '吹きさらしのサバンナ',
    wooded_badlands: '森のある荒野',
    wooded_hills: '森のある丘',
    giant_spruce_taiga: '巨大トウヒタイガ',
    giant_tree_taiga: '巨大樹タイガ',
    gravelly_mountains: '砂利の山',
    jungle_edge: 'ジャングルの端',
    mountains: '山岳',
    shattered_savanna: '荒廃したサバンナ',
    snowy_tundra: '雪のツンドラ',
    stone_shore: '石の海岸',
    tall_birch_forest: 'シラカバ原生林',
    wooded_badlands_plateau: '森のある荒野の台地',
    wooded_mountains: '森のある山',
  },
  ru: {
    badlands: 'Бесплодные земли',
    badlands_plateau: 'Плато бесплодных земель',
    bamboo_jungle: 'Бамбуковые джунгли',
    bamboo_jungle_hills: 'Холмистые бамбуковые джунгли',
    basalt_deltas: 'Базальтовые дельты',
    beach: 'Пляж',
    birch_forest: 'Берёзовый лес',
    birch_forest_hills: 'Холмистый берёзовый лес',
    cherry_grove: 'Вишнёвая роща',
    cold_ocean: 'Холодный океан',
    crimson_forest: 'Багровый лес',
    dark_forest: 'Тёмный лес',
    dark_forest_hills: 'Холмистый тёмный лес',
    deep_cold_ocean: 'Глубокий холодный океан',
    deep_dark: 'Глубинный мрак',
    deep_frozen_ocean: 'Глубокий замёрзший океан',
    deep_lukewarm_ocean: 'Глубокий умеренный океан',
    deep_ocean: 'Глубокий океан',
    deep_warm_ocean: 'Глубокий тёплый океан',
    desert: 'Пустыня',
    desert_hills: 'Холмистая пустыня',
    desert_lakes: 'Пустынные озёра',
    dripstone_caves: 'Карстовые пещеры',
    end_barrens: 'Пустоши Края',
    end_highlands: 'Высокогорья Края',
    end_midlands: 'Срединные земли Края',
    eroded_badlands: 'Выветренные бесплодные земли',
    flower_forest: 'Цветочный лес',
    forest: 'Лес',
    frozen_ocean: 'Замёрзший океан',
    frozen_peaks: 'Ледяные пики',
    frozen_river: 'Замёрзшая река',
    giant_spruce_taiga_hills: 'Холмистая гигантская еловая тайга',
    giant_tree_taiga_hills: 'Холмистая тайга гигантских деревьев',
    grove: 'Роща',
    ice_spikes: 'Ледяные шипы',
    jagged_peaks: 'Зубчатые пики',
    jungle: 'Джунгли',
    jungle_hills: 'Холмистые джунгли',
    lukewarm_ocean: 'Умеренный океан',
    lush_caves: 'Пышные пещеры',
    mangrove_swamp: 'Мангровое болото',
    meadow: 'Луг',
    modified_badlands_plateau: 'Изменённое плато бесплодных земель',
    modified_gravelly_mountains: 'Изменённые гравийные горы',
    modified_jungle: 'Изменённые джунгли',
    modified_jungle_edge: 'Изменённая окраина джунглей',
    modified_wooded_badlands_plateau: 'Изменённое лесистое плато бесплодных земель',
    mountain_edge: 'Горная опушка',
    mushroom_field_shore: 'Берег грибных полей',
    mushroom_fields: 'Грибные поля',
    nether_wastes: 'Пустоши Нижнего мира',
    ocean: 'Океан',
    old_growth_birch_forest: 'Старый берёзовый лес',
    old_growth_pine_taiga: 'Старая сосновая тайга',
    old_growth_spruce_taiga: 'Старая еловая тайга',
    pale_garden: 'Бледный сад',
    plains: 'Равнины',
    rainforest: 'Тропический лес',
    river: 'Река',
    savanna: 'Саванна',
    savanna_plateau: 'Плато саванны',
    seasonal_forest: 'Сезонный лес',
    shattered_savanna_plateau: 'Разрушенное плато саванны',
    shrubland: 'Кустарники',
    small_end_islands: 'Малые острова Края',
    snowy_beach: 'Заснеженный пляж',
    snowy_mountains: 'Заснеженные горы',
    snowy_plains: 'Заснеженные равнины',
    snowy_slopes: 'Заснеженные склоны',
    snowy_taiga: 'Заснеженная тайга',
    snowy_taiga_hills: 'Холмистая заснеженная тайга',
    snowy_taiga_mountains: 'Горная заснеженная тайга',
    soul_sand_valley: 'Долина песка душ',
    sparse_jungle: 'Редкие джунгли',
    stony_peaks: 'Каменистые пики',
    stony_shore: 'Каменистый берег',
    sunflower_plains: 'Подсолнечные равнины',
    swamp: 'Болото',
    swamp_hills: 'Холмистое болото',
    taiga: 'Тайга',
    taiga_hills: 'Холмистая тайга',
    taiga_mountains: 'Горная тайга',
    tall_birch_hills: 'Холмы высокого берёзового леса',
    the_end: 'Край',
    the_void: 'Пустота',
    warm_ocean: 'Тёплый океан',
    warped_forest: 'Искажённый лес',
    windswept_forest: 'Продуваемый лес',
    windswept_gravelly_hills: 'Продуваемые гравийные холмы',
    windswept_hills: 'Продуваемые холмы',
    windswept_savanna: 'Продуваемая саванна',
    wooded_badlands: 'Лесистые бесплодные земли',
    wooded_hills: 'Лесистые холмы',
    giant_spruce_taiga: 'Гигантская еловая тайга',
    giant_tree_taiga: 'Тайга гигантских деревьев',
    gravelly_mountains: 'Гравийные горы',
    jungle_edge: 'Окраина джунглей',
    mountains: 'Горы',
    shattered_savanna: 'Разрушенная саванна',
    snowy_tundra: 'Заснеженная тундра',
    stone_shore: 'Каменистый берег',
    tall_birch_forest: 'Высокий берёзовый лес',
    wooded_badlands_plateau: 'Лесистое плато бесплодных земель',
    wooded_mountains: 'Лесистые горы',
  },
  pl: {
    badlands: 'Badlandy',
    badlands_plateau: 'Płaskowyż badlandów',
    bamboo_jungle: 'Bambusowa dżungla',
    bamboo_jungle_hills: 'Wzgórza bambusowej dżungli',
    basalt_deltas: 'Bazaltowe delty',
    beach: 'Plaża',
    birch_forest: 'Las brzozowy',
    birch_forest_hills: 'Wzgórza lasu brzozowego',
    cherry_grove: 'Wiśniowy gaj',
    cold_ocean: 'Zimny ocean',
    crimson_forest: 'Szkarłatny las',
    dark_forest: 'Mroczny las',
    dark_forest_hills: 'Wzgórza mrocznego lasu',
    deep_cold_ocean: 'Głęboki zimny ocean',
    deep_dark: 'Głęboki mrok',
    deep_frozen_ocean: 'Głęboki zamarznięty ocean',
    deep_lukewarm_ocean: 'Głęboki letni ocean',
    deep_ocean: 'Głęboki ocean',
    deep_warm_ocean: 'Głęboki ciepły ocean',
    desert: 'Pustynia',
    desert_hills: 'Pustynne wzgórza',
    desert_lakes: 'Pustynne jeziora',
    dripstone_caves: 'Naciekowe jaskinie',
    end_barrens: 'Jałowe ziemie Kresu',
    end_highlands: 'Wyżyny Kresu',
    end_midlands: 'Śródziemia Kresu',
    eroded_badlands: 'Zerodowane badlandy',
    flower_forest: 'Kwietny las',
    forest: 'Las',
    frozen_ocean: 'Zamarznięty ocean',
    frozen_peaks: 'Oblodzone szczyty',
    frozen_river: 'Zamarznięta rzeka',
    giant_spruce_taiga_hills: 'Wzgórza gigantycznej świerkowej tajgi',
    giant_tree_taiga_hills: 'Wzgórza tajgi gigantycznych drzew',
    grove: 'Zagajnik',
    ice_spikes: 'Lodowe kolce',
    jagged_peaks: 'Postrzępione szczyty',
    jungle: 'Dżungla',
    jungle_hills: 'Wzgórza dżungli',
    lukewarm_ocean: 'Letni ocean',
    lush_caves: 'Bujne jaskinie',
    mangrove_swamp: 'Namorzynowe bagno',
    meadow: 'Łąka',
    modified_badlands_plateau: 'Zmodyfikowany płaskowyż badlandów',
    modified_gravelly_mountains: 'Zmodyfikowane żwirowe góry',
    modified_jungle: 'Zmodyfikowana dżungla',
    modified_jungle_edge: 'Zmodyfikowany skraj dżungli',
    modified_wooded_badlands_plateau: 'Zmodyfikowany zalesiony płaskowyż badlandów',
    mountain_edge: 'Skraj gór',
    mushroom_field_shore: 'Brzeg grzybowych pól',
    mushroom_fields: 'Grzybowe pola',
    nether_wastes: 'Netherowe pustkowia',
    ocean: 'Ocean',
    old_growth_birch_forest: 'Starodrzew brzozowy',
    old_growth_pine_taiga: 'Starodrzew sosnowej tajgi',
    old_growth_spruce_taiga: 'Starodrzew świerkowej tajgi',
    pale_garden: 'Blady ogród',
    plains: 'Równiny',
    rainforest: 'Las deszczowy',
    river: 'Rzeka',
    savanna: 'Sawanna',
    savanna_plateau: 'Płaskowyż sawanny',
    seasonal_forest: 'Las sezonowy',
    shattered_savanna_plateau: 'Roztrzaskany płaskowyż sawanny',
    shrubland: 'Zarośla',
    small_end_islands: 'Małe wyspy Kresu',
    snowy_beach: 'Ośnieżona plaża',
    snowy_mountains: 'Ośnieżone góry',
    snowy_plains: 'Ośnieżone równiny',
    snowy_slopes: 'Ośnieżone zbocza',
    snowy_taiga: 'Ośnieżona tajga',
    snowy_taiga_hills: 'Wzgórza ośnieżonej tajgi',
    snowy_taiga_mountains: 'Góry ośnieżonej tajgi',
    soul_sand_valley: 'Dolina piasku dusz',
    sparse_jungle: 'Rzadka dżungla',
    stony_peaks: 'Kamieniste szczyty',
    stony_shore: 'Kamienisty brzeg',
    sunflower_plains: 'Słonecznikowe równiny',
    swamp: 'Bagno',
    swamp_hills: 'Bagienne wzgórza',
    taiga: 'Tajga',
    taiga_hills: 'Wzgórza tajgi',
    taiga_mountains: 'Góry tajgi',
    tall_birch_hills: 'Wzgórza wysokiego lasu brzozowego',
    the_end: 'Kres',
    the_void: 'Pustka',
    warm_ocean: 'Ciepły ocean',
    warped_forest: 'Spaczony las',
    windswept_forest: 'Wietrzny las',
    windswept_gravelly_hills: 'Wietrzne żwirowe wzgórza',
    windswept_hills: 'Wietrzne wzgórza',
    windswept_savanna: 'Wietrzna sawanna',
    wooded_badlands: 'Zalesione badlandy',
    wooded_hills: 'Zalesione wzgórza',
    giant_spruce_taiga: 'Gigantyczna świerkowa tajga',
    giant_tree_taiga: 'Tajga gigantycznych drzew',
    gravelly_mountains: 'Żwirowe góry',
    jungle_edge: 'Skraj dżungli',
    mountains: 'Góry',
    shattered_savanna: 'Roztrzaskana sawanna',
    snowy_tundra: 'Ośnieżona tundra',
    stone_shore: 'Kamienny brzeg',
    tall_birch_forest: 'Wysoki las brzozowy',
    wooded_badlands_plateau: 'Zalesiony płaskowyż badlandów',
    wooded_mountains: 'Zalesione góry',
  },
  'zh-CN': {
    badlands: '恶地',
    badlands_plateau: '恶地高原',
    bamboo_jungle: '竹林',
    bamboo_jungle_hills: '竹林丘陵',
    basalt_deltas: '玄武岩三角洲',
    beach: '沙滩',
    birch_forest: '白桦森林',
    birch_forest_hills: '白桦森林丘陵',
    cherry_grove: '樱花树林',
    cold_ocean: '冷水海洋',
    crimson_forest: '绯红森林',
    dark_forest: '黑森林',
    dark_forest_hills: '黑森林丘陵',
    deep_cold_ocean: '冷水深海',
    deep_dark: '深暗之域',
    deep_frozen_ocean: '冰冻深海',
    deep_lukewarm_ocean: '温水深海',
    deep_ocean: '深海',
    deep_warm_ocean: '暖水深海',
    desert: '沙漠',
    desert_hills: '沙漠丘陵',
    desert_lakes: '沙漠湖泊',
    dripstone_caves: '溶洞',
    end_barrens: '末地荒地',
    end_highlands: '末地高地',
    end_midlands: '末地内陆',
    eroded_badlands: '风蚀恶地',
    flower_forest: '繁花森林',
    forest: '森林',
    frozen_ocean: '冻洋',
    frozen_peaks: '冰封山峰',
    frozen_river: '冻河',
    giant_spruce_taiga_hills: '巨型云杉针叶林丘陵',
    giant_tree_taiga_hills: '巨型针叶林丘陵',
    grove: '雪林',
    ice_spikes: '冰刺之地',
    jagged_peaks: '尖峭山峰',
    jungle: '丛林',
    jungle_hills: '丛林丘陵',
    lukewarm_ocean: '温水海洋',
    lush_caves: '繁茂洞穴',
    mangrove_swamp: '红树林沼泽',
    meadow: '草甸',
    modified_badlands_plateau: '恶地高原变种',
    modified_gravelly_mountains: '沙砾山丘变种',
    modified_jungle: '丛林变种',
    modified_jungle_edge: '丛林边缘变种',
    modified_wooded_badlands_plateau: '繁茂恶地高原变种',
    mountain_edge: '山地边缘',
    mushroom_field_shore: '蘑菇岛岸',
    mushroom_fields: '蘑菇岛',
    nether_wastes: '下界荒地',
    ocean: '海洋',
    old_growth_birch_forest: '原始桦木森林',
    old_growth_pine_taiga: '原始松木针叶林',
    old_growth_spruce_taiga: '原始云杉针叶林',
    pale_garden: '苍白之园',
    plains: '平原',
    rainforest: '雨林',
    river: '河流',
    savanna: '热带草原',
    savanna_plateau: '热带高原',
    seasonal_forest: '季节性森林',
    shattered_savanna_plateau: '破碎的热带高原',
    shrubland: '灌木丛',
    small_end_islands: '末地小型岛屿',
    snowy_beach: '积雪沙滩',
    snowy_mountains: '雪山',
    snowy_plains: '雪原',
    snowy_slopes: '积雪山坡',
    snowy_taiga: '积雪针叶林',
    snowy_taiga_hills: '积雪针叶林丘陵',
    snowy_taiga_mountains: '积雪针叶林山地',
    soul_sand_valley: '灵魂沙峡谷',
    sparse_jungle: '稀疏丛林',
    stony_peaks: '裸岩山峰',
    stony_shore: '石岸',
    sunflower_plains: '向日葵平原',
    swamp: '沼泽',
    swamp_hills: '沼泽丘陵',
    taiga: '针叶林',
    taiga_hills: '针叶林丘陵',
    taiga_mountains: '针叶林山地',
    tall_birch_hills: '高大桦木丘陵',
    the_end: '末地',
    the_void: '虚空',
    warm_ocean: '暖水海洋',
    warped_forest: '诡异森林',
    windswept_forest: '风袭森林',
    windswept_gravelly_hills: '风袭沙砾丘陵',
    windswept_hills: '风袭丘陵',
    windswept_savanna: '风袭热带草原',
    wooded_badlands: '疏林恶地',
    wooded_hills: '繁茂丘陵',
    giant_spruce_taiga: '巨型云杉针叶林',
    giant_tree_taiga: '巨型针叶林',
    gravelly_mountains: '沙砾山丘',
    jungle_edge: '丛林边缘',
    mountains: '山地',
    shattered_savanna: '破碎的热带草原',
    snowy_tundra: '积雪冻原',
    stone_shore: '石头海岸',
    tall_birch_forest: '高大桦木森林',
    wooded_badlands_plateau: '繁茂恶地高原',
    wooded_mountains: '繁茂山地',
  },
  'zh-TW': {
    badlands: '惡地',
    badlands_plateau: '惡地高原',
    bamboo_jungle: '竹林',
    bamboo_jungle_hills: '竹林丘陵',
    basalt_deltas: '玄武岩三角洲',
    beach: '沙灘',
    birch_forest: '樺木森林',
    birch_forest_hills: '樺木森林丘陵',
    cherry_grove: '櫻花樹林',
    cold_ocean: '寒冷海洋',
    crimson_forest: '緋紅森林',
    dark_forest: '黑森林',
    dark_forest_hills: '黑森林丘陵',
    deep_cold_ocean: '寒冷深海',
    deep_dark: '深淵',
    deep_frozen_ocean: '寒凍深海',
    deep_lukewarm_ocean: '溫和深海',
    deep_ocean: '深海',
    deep_warm_ocean: '溫暖深海',
    desert: '沙漠',
    desert_hills: '沙漠丘陵',
    desert_lakes: '沙漠湖泊',
    dripstone_caves: '鐘乳石洞窟',
    end_barrens: '終界荒地',
    end_highlands: '終界高地',
    end_midlands: '終界平地',
    eroded_badlands: '侵蝕惡地',
    flower_forest: '繁花森林',
    forest: '森林',
    frozen_ocean: '寒凍海洋',
    frozen_peaks: '霜凍山峰',
    frozen_river: '寒凍河流',
    giant_spruce_taiga_hills: '巨型杉木針葉林丘陵',
    giant_tree_taiga_hills: '巨型針葉林丘陵',
    grove: '雪林',
    ice_spikes: '冰刺',
    jagged_peaks: '尖峭山峰',
    jungle: '叢林',
    jungle_hills: '叢林丘陵',
    lukewarm_ocean: '溫和海洋',
    lush_caves: '蒼鬱洞窟',
    mangrove_swamp: '紅樹林沼澤',
    meadow: '草甸',
    modified_badlands_plateau: '惡地高原變種',
    modified_gravelly_mountains: '礫質丘陵變種',
    modified_jungle: '叢林變種',
    modified_jungle_edge: '叢林邊緣變種',
    modified_wooded_badlands_plateau: '疏林惡地高原變種',
    mountain_edge: '山地邊緣',
    mushroom_field_shore: '蘑菇地海岸',
    mushroom_fields: '蘑菇地',
    nether_wastes: '地獄荒原',
    ocean: '海洋',
    old_growth_birch_forest: '原生樺木森林',
    old_growth_pine_taiga: '原生松木針葉林',
    old_growth_spruce_taiga: '原生杉木針葉林',
    pale_garden: '蒼白之園',
    plains: '平原',
    rainforest: '雨林',
    river: '河流',
    savanna: '莽原',
    savanna_plateau: '莽原高地',
    seasonal_forest: '季節森林',
    shattered_savanna_plateau: '破碎莽原高地',
    shrubland: '灌木地',
    small_end_islands: '終界小島',
    snowy_beach: '冰雪沙灘',
    snowy_mountains: '冰雪山地',
    snowy_plains: '雪原',
    snowy_slopes: '雪坡',
    snowy_taiga: '冰雪針葉林',
    snowy_taiga_hills: '冰雪針葉林丘陵',
    snowy_taiga_mountains: '冰雪針葉林山地',
    soul_sand_valley: '靈魂砂谷',
    sparse_jungle: '稀疏叢林',
    stony_peaks: '裸岩山峰',
    stony_shore: '石岸',
    sunflower_plains: '向日葵平原',
    swamp: '沼澤',
    swamp_hills: '沼澤丘陵',
    taiga: '針葉林',
    taiga_hills: '針葉林丘陵',
    taiga_mountains: '針葉林山地',
    tall_birch_hills: '高大樺木丘陵',
    the_end: '終界',
    the_void: '虛空',
    warm_ocean: '溫暖海洋',
    warped_forest: '扭曲森林',
    windswept_forest: '風蝕森林',
    windswept_gravelly_hills: '風蝕礫質丘陵',
    windswept_hills: '風蝕丘陵',
    windswept_savanna: '風蝕莽原',
    wooded_badlands: '疏林惡地',
    wooded_hills: '疏林丘陵',
    giant_spruce_taiga: '巨型杉木針葉林',
    giant_tree_taiga: '巨型針葉林',
    gravelly_mountains: '礫質丘陵',
    jungle_edge: '叢林邊緣',
    mountains: '山地',
    shattered_savanna: '破碎莽原',
    snowy_tundra: '冰雪凍原',
    stone_shore: '石礫海岸',
    tall_birch_forest: '高大樺木森林',
    wooded_badlands_plateau: '疏林惡地高原',
    wooded_mountains: '疏林山地',
  },
};

// "cherry_grove" -> "Cherry Grove"; matches the official English biome names.
export function prettifyBiome(name) {
  return String(name).split('_').map((w) => (w ? w[0].toUpperCase() + w.slice(1) : w)).join(' ');
}

// Localized label for a technical biome name; lang defaults to the UI
// language (currentLang from i18n.js), unknown entries fall back to English.
export function biomeLabel(name, lang) {
  const l = lang || currentLang();
  return BIOME_NAMES[l]?.[name] || prettifyBiome(name);
}
